services:
  postgres:
    image: postgres:latest
    container_name: advanceddb_02assignment_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  load_generator:
    image: python:slim
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: postgres
    command: >
      sh -c "pip install --no-cache-dir psycopg2-binary faker && python load_assignment_generator.py"

volumes:
  pgdata: